// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGq-mZ-m8OU0DSC6--O3BIHUcLluYkqUw',
    appId: '1:303337035628:web:a9d866c3b728aadefa8549',
    messagingSenderId: '303337035628',
    projectId: 'led-controller-55f1c',
    authDomain: 'led-controller-55f1c.firebaseapp.com',
    storageBucket: 'led-controller-55f1c.firebasestorage.app',
    measurementId: 'G-L5P2PV5TJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqnugSnaYqVQ7tQpfApvhF8yUrnbp9sCg',
    appId: '1:303337035628:android:a38722bdaa45d1bffa8549',
    messagingSenderId: '303337035628',
    projectId: 'led-controller-55f1c',
    storageBucket: 'led-controller-55f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT5vJE9AoGwG7xDPCwDoslbemoFxzLpe8',
    appId: '1:303337035628:ios:b67ad262f60e654afa8549',
    messagingSenderId: '303337035628',
    projectId: 'led-controller-55f1c',
    storageBucket: 'led-controller-55f1c.firebasestorage.app',
    iosBundleId: 'com.example.ledController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT5vJE9AoGwG7xDPCwDoslbemoFxzLpe8',
    appId: '1:303337035628:ios:b67ad262f60e654afa8549',
    messagingSenderId: '303337035628',
    projectId: 'led-controller-55f1c',
    storageBucket: 'led-controller-55f1c.firebasestorage.app',
    iosBundleId: 'com.example.ledController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGq-mZ-m8OU0DSC6--O3BIHUcLluYkqUw',
    appId: '1:303337035628:web:393e9afd9f868e28fa8549',
    messagingSenderId: '303337035628',
    projectId: 'led-controller-55f1c',
    authDomain: 'led-controller-55f1c.firebaseapp.com',
    storageBucket: 'led-controller-55f1c.firebasestorage.app',
    measurementId: 'G-5Q6W9XPBVW',
  );
}
